### ISSUE TITLE
[bug]: unable to configure external tor bitcoind

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/btc-rpc-proxy-wrapper#20]
just tons of this in the logs:

`2022-03-31T18:33:05.604516Z Mar 31 18:33:05.603 WARN failed request, error_message: hyper failed to process HTTP request, error_code: -1, method: getblockchaininfo, user: lnd, params: []`

**Comment by ProofOfKeags** [comment]
is this irrespective of whether bitcoind is tor vs clearnet?

**Comment by chrisguida** [comment]
No, clearnet works as of this PR https://github.com/Start9Labs/btc-rpc-proxy-wrapper/pull/19

Tor is still broken

**Comment by ProofOfKeags** [comment]
Closing since we are ripping this feature out.

**Comment by chrisguida** [comment]
Are we not planning to fix external tor connections?

**Comment by ProofOfKeags** [comment]
I think it is unwise for us to actually spend effort on this use case since obviously no one is using it. We will reevaluate this if/when customers desire it.
