### ISSUE TITLE
[fix]: Move object of pointers to top level

### ISSUE THREAD

**Issue by elvece** [Start9Labs/btc-rpc-proxy-wrapper#24]
Since external was removed as an option from [this](https://github.com/Start9Labs/btc-rpc-proxy-wrapper/blob/93f6f4a00a58a01c665b4aac0f1e37dfd37f837e/assets/compat/config_spec.yaml#L9-L31) section of the config, we now have an empty section displaying in the UI as this object is solely pointers.

<img width="526" alt="Screen Shot 2022-04-25 at 11 54 51 AM" src="https://user-images.githubusercontent.com/12953208/165146116-78b6c741-6629-4803-8e4e-9b5e7d2a4e6b.png">

Solution: move the pointers up one level (out of the object) to some value like `bitcoind-user` and `bitcoind-password` so that they can still exist as references in the config file, but not display in the UI (since at the top level, we filter out pointers)

Filtering out pointers at lower levels is potentially non-trivial, the ticket tracking that implementation can be found [here](https://github.com/Start9Labs/embassy-os/issues/1398).

**Comment by ProofOfKeags** [comment]
This upsets me.

**Comment by chrisguida** [comment]
> This upsets me. See [Start9Labs/embassy-os#1398](https://github.com/Start9Labs/embassy-os/issues/1398) for why.

This seems like a sensible solution
