### ISSUE TITLE
Make "fetch-blocks" config required for users with "getblock" command allowed.

### ISSUE THREAD

**Issue by yzernik** [Start9Labs/btc-rpc-proxy-wrapper#25]
Currently, the rule says

> All users with "Fetch Blocks" enabled must allow the "getblock" RPC command.

https://github.com/Start9Labs/btc-rpc-proxy-wrapper/blob/bca409596f1b5b109e597aff0606944f06d28818/assets/compat/config_rules.yaml#L1-L2

This seems backwards to me. I think it should be

> All users with "getblock" RPC command allowed must have "Fetch Blocks" enabled.

**Comment by yzernik** [comment]
So i think the new rule would be something like:

```
'''users.[all(user => user.allowed-calls.* = "getblock")].fetch-blocks?'
```

**Comment by yzernik** [comment]
What happens if you have `fetch-blocks` set to false, and `getblock` in the allowed calls list?

Wouldn't every call to `getblock` fail if the block is not in the local pruned node?

**Comment by ProofOfKeags** [comment]
> Wouldn't every call to getblock fail if the block is not in the local pruned node?

No. Just the ones that are outside of the pruned set. Recent blocks will be available. Depending on the size of your prune cache, it could even be most of them that are available.

That said, I'm not sure how many clients are able to dynamically handle some subset of the blockchain being unavailable from the RPC node.
