### ISSUE TITLE
Make bitcoind a critical dependency for proxy. Check other services to see if this applies to them as well.

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/btc-rpc-proxy-wrapper#9]

**Comment by dr-bonez** [comment]
Dependencies should only be marked as critical if:

1. The application will crash if the dependency is not working propery
2. The application will perform undesired or undefined behavior if the dependency is not working properly

This does not apply to btc-rpc-proxy -> bitcoind

**Comment by chrisguida** [comment]
Can you elaborate? Seems like proxy will "perform undesired or undefined behavior" if bitcoind is down. Can you give an example of which services *do* need to be critical dependencies?

**Comment by ProofOfKeags** [comment]
Critical dependencies are defined as those where it is *dangerous* to run them if the dependency health check is failing. Proxy does not actually have any agency and doesn't make any decisions for which bitcoind is the source of truth. It actually makes no decisions at all. As such it doesn't make sense for it to have a critical dependency on anything.

**Comment by chrisguida** [comment]
@dr-bonez @ProofOfKeags can you give an example of when something *should* be a critical dependency?

**Comment by ProofOfKeags** [comment]
I am not sure we have any in our current stack. I'm not sure why an example is needed when the criteria have been outlined. Danger can be understood as data loss (and by extension funds loss) that has a nontrivial likelihood as a result of the health check failing.

**Comment by chrisguida** [comment]
@dr-bonez @ProofOfKeags Why do we have a feature that isn't needed for any of our services? Are we likely to have any services that need this feature? If not, it's just confusing.

**Comment by dr-bonez** [comment]
c-lightning needs this for bitcoin, because it will go into a crash loop if it's not available, spamming the user with notifications.

**Comment by ProofOfKeags** [comment]
>  Are we likely to have any services that need this feature? If not, it's just confusing.

Looks like we do now according to @dr-bonez.

Having protections for scenarios that are dangerous is a good thing. Also it seems like anything that will cause a crash loop is now in scope for "critical"

**Comment by chrisguida** [comment]
@dr-bonez would that not work as a critical health check?

**Comment by chrisguida** [comment]
@dr-bonez Also am I correct in assuming that c-lightning's dependency requirement for bitcoind should be set to "opt-out"? How do we signal to the OS that bitcoind needs to be full archival in order not to require proxy?

**Comment by chrisguida** [comment]
@dr-bonez says that, if we have a service that depends critically on another service, that should always be implemented as a critical dependency because the UX will be better since this is what critical dependencies were designed for.
